sudo: false
dist: trusty
language: generic
env:
  global:
    - SAMBADA_VERSION=0.8.0alpha4

matrix:
  include:
  - os: linux
    env:
      - SAMBADA_OS_NAME=ubuntu
      - MATRIX_EVAL=""
      - SAMBADA_TEST_TYPE=SMOKE
  - os: linux
    env:
      - SAMBADA_OS_NAME=ubuntu
      - MATRIX_EVAL=""
      - SAMBADA_TEST_TYPE=INTEGRATION
  - os: osx
    env:
      - SAMBADA_OS_NAME=${TRAVIS_OS_NAME}
      - MATRIX_EVAL="brew install gcc@7 && CC=gcc-7 && CXX=g++-7"
      - SAMBADA_TEST_TYPE=SMOKE
  - os: osx
    env:
      - SAMBADA_OS_NAME=${TRAVIS_OS_NAME}
      - MATRIX_EVAL="brew install gcc@7 && CC=gcc-7 && CXX=g++-7"
      - SAMBADA_TEST_TYPE=INTEGRATION
before_install:
    - eval "${MATRIX_EVAL}"
git:
  depth: 100
script: travis-build.sh
