sudo: false
dist: trusty
language: generic
env:
  global:
    - SAMBADA_VERSION=0.6.1alpha2

matrix:
  include:
  - os: linux
    env:
      - SAMBADA_OS_NAME=ubuntu
      - MATRIX_EVAL=""
  - os: osx
    env:
      - SAMBADA_OS_NAME=${TRAVIS_OS_NAME}
      - MATRIX_EVAL="brew cask uninstall oclint && brew install gcc@7 && CC=gcc-7 && CXX=g++-7"
before_install:
    - eval "${MATRIX_EVAL}"
git:
  depth: 100
script:
  - echo ${SAMBADA_VERSION} ${SAMBADA_OS_NAME}
  - PACKAGE_NAME=sambada-${SAMBADA_VERSION}-${SAMBADA_OS_NAME}
  - wget "https://github.com/Sylvie/sambada/releases/download/v${SAMBADA_VERSION}/${PACKAGE_NAME}.tar.gz"
  - tar -zxvf $PACKAGE_NAME.tar.gz
  - cd ${PACKAGE_NAME}/examples/subset-cattle-SNP
  - ../../binaries/sambada param-cattle.txt cattle-env.csv cattle-mark.txt
  - head  cattle-mark-Out-1.txt
