sudo: false
dist: trusty
language: generic
env:
  global:
    - SAMBADA_VERSION=0.8.0alpha4

matrix:
  include:
  - os: linux
    compiler: gcc
    env:
      - SAMBADA_OS_NAME=ubuntu
      - MATRIX_EVAL=""
      - SAMBADA_TEST_TYPE=SMOKE
  - os: linux
    compiler: gcc
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-7
    env:
      - SAMBADA_OS_NAME=ubuntu
      - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      - SAMBADA_TEST_TYPE=INTEGRATION
  - os: osx
    compiler: gcc
    env:
      - SAMBADA_OS_NAME=${TRAVIS_OS_NAME}
      - MATRIX_EVAL="brew install gcc@7 && CC=gcc-7 && CXX=g++-7"
      - SAMBADA_TEST_TYPE=SMOKE
  - os: osx
    compiler: gcc
    env:
      - SAMBADA_OS_NAME=${TRAVIS_OS_NAME}
      - MATRIX_EVAL="brew install gcc@7 && CC=gcc-7 && CXX=g++-7"
      - SAMBADA_TEST_TYPE=INTEGRATION
before_install:
    - eval "${MATRIX_EVAL}"
git:
  depth: 100
script: ./travis-build.sh
